default:
  image: maven:3.6.3-jdk-11

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean compile assembly:single
    - mvn package
  artifacts:
    paths:
    - target/pokedex-back-1.0-SNAPSHOT-jar-with-dependencies.jar
    when: on_success
    expire_in: "30 days"

integration_tests:
  stage: test
  script:
    - java -jar target/pokedex-back-1.0-SNAPSHOT-jar-with-dependencies.jar &
    - cd integration_test
    - apt-get update
    - apt-get install python3-pytest python3-requests -y
    - pytest-3